### ISSUE TITLE
ddev-router not working

### ISSUE THREAD

**Issue by luksak** [Mogtofu33/contenta-ddev#2]
I installed contenta-ddev using the provided install.sh. When visiting contentajs.ddev.local and front-vue.ddev.local I get this message:

```
502: Unresponsive/broken ddev back-end site.

This is the ddev-router container: The back-end webserver at the URL you specified is not responding. You may want to use "ddev restart" to restart the site.
```

**Comment by Mogtofu33** [comment]
You have to wait a bit, at least ~2min or restart.
You can check at http://contenta.ddev.local:9000

**Comment by luksak** [comment]
Sorry, I realized that after some time it does respond but with a different error:
```
503: No ddev back-end site available.
This is the ddev-router container: There is no back-end webserver at the URL you specified. You may want to use "ddev start" to start the site.
```
What could be the issue for this?
